module.exports = {
    PrimitiveTypes : [
        "instant" , 
        "time" , 
        "date" , 
        "dateTime" , 
        "base64Binary" ,
        "decimal" ,
        "boolean" ,
        "url" ,
        "code" ,
        "string" ,
        "integer" ,
        "uri" ,
        "canonical" ,
        "markdown" ,
        "id" ,
        "oid" ,
        "uuid" ,
        "unsignedInt" ,
        "positiveInt"
    ] ,
    GeneralPurposeDataTypes : [
        "Ratio",
        "Period",
        "Range",
        "Attachment",
        "Identifier",
        "Annotation",
        "HumanName",
        "CodeableConcept",
        "ContactPoint",
        "Coding",
        "Money",
        "Address",
        "Timing",
        "BackboneElement",
        "Quantity",
        "SampledData",
        "Signature",
        "Age",
        "Distance",
        "Duration",
        "Count",
        "MoneyQuantity",
        "SimpleQuantity",
    ] ,
    MetadataTypes: [
        "ContactDetail",
        "Contributor",
        "DataRequirement",
        "RelatedArtifact",
        "UsageContext",
        "ParameterDefinition",
        "Expression",
        "TriggerDefinition",
    ] ,
    SpecialPurposeDataTypes: [
        "Reference" ,
        "Meta" ,
        "Dosage" ,
        "xhtml" ,
        "BackboneElement" ,
        "Narrative" ,
        "Extension" ,
        "ElementDefinition"
    ]
};